"""fix download_links e timezone

Revision ID: 47ed9c8d4dce
Revises: 822855b818cc
Create Date: 2025-11-24 18:38:22.530021+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import necessário para TIMESTAMP(timezone=True)


# revision identifiers, used by Alembic.
revision: str = '47ed9c8d4dce'
down_revision: Union[str, None] = '822855b818cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Recriação da tabela download_links (que foi perdida na migração a6ba9fc487cc)
    op.create_table('download_links',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        # Correção do timezone para 'expires_at'
        sa.Column('expires_at', sa.DateTime(timezone=True), autoincrement=False, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='download_links_pkey')
    )

    # 2. Correção do timezone na tabela token_denylist (se a coluna não for TIMESTAMP WITH TIMEZONE)
    # Este é um ALTER COLUMN complexo no PostgreSQL e pode exigir comandos brutos de SQL.
    # Se você já corrigiu o modelo, o Alembic deveria ter gerado isso.
    # Se precisar forçar a mudança do tipo da coluna:
    # op.alter_column('token_denylist', 'expires_at',
    #                existing_type=sa.DateTime(),
    #                type_=sa.DateTime(timezone=True),
    #                existing_nullable=False,
    #                postgresql_using="expires_at AT TIME ZONE 'UTC'")

    # Se a intenção era criar uma nova coluna, use o código do seu modelo.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download_links')

    # op.alter_column('token_denylist', 'expires_at',
    #                existing_type=sa.DateTime(timezone=True),
    #                type_=sa.DateTime(),
    #                existing_nullable=False,
    #                postgresql_using="expires_at AT TIME ZONE 'UTC'")
    pass
    # ### end Alembic commands ###