"""Adiciona campos de data, hora e participantes a events

Revision ID: ac18f0285bd3
Revises: 1904642a0260
Create Date: 2025-10-12 14:23:14.849538+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac18f0285bd3'
down_revision: Union[str, None] = '1904642a0260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('participants_count', sa.Integer(), nullable=True))
    op.drop_constraint('metrics_user_id_fkey', 'metrics', type_='foreignkey')
    op.create_foreign_key(None, 'metrics', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.create_foreign_key('metrics_user_id_fkey', 'metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'participants_count')
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###
