"""make s3_url nullable on photos

Revision ID: be3bbf44cf8d
Revises: e5dcc058569c
Create Date: 2025-11-24 19:07:33.421442+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be3bbf44cf8d'
down_revision: Union[str, None] = 'e5dcc058569c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 's3_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 's3_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
