"""add user boolean consent fields

Revision ID: f5cfd5d0ee51
Revises: d1b5087105a4
Create Date: 2025-09-28 18:38:52.132633+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cfd5d0ee51'
down_revision: Union[str, None] = 'd1b5087105a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biometric_acceptance', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('international_transfer_data', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('image_usage_portifolio', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('marketing_communication_usage', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('age_declaration', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('responsible_consent', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'responsible_consent')
    op.drop_column('users', 'age_declaration')
    op.drop_column('users', 'marketing_communication_usage')
    op.drop_column('users', 'image_usage_portifolio')
    op.drop_column('users', 'international_transfer_data')
    op.drop_column('users', 'biometric_acceptance')
    # ### end Alembic commands ###
